#common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: ZTc5YTY5MWJmYWI2MGU2ZjBkMGM4NzE5NjdhZmU0ZTg1OTUxNjM0MDVkNGVjNThmY2VmOWE5ZGM5MmZhMmE5OTlhNjNiYTQxOWViOTgyMDkzODE4OGRhOGRmMjI4NDcwNmExMg==
management:
  metrics:
    export:
      prometheus:
        enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
